---
title: "setup"
author: "Andrew Tu"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(usmap)
library(ggpmisc)
library(plotly)
# 
# 
# county_SVI = read_csv(
#   url('https://svi.cdc.gov/Documents/Data/2020_SVI_Data/CSV/SVI2020_US_COUNTY.csv')
#   )%>%
#   write_csv('SVI2020_US_COUNTY.csv')
# 
# census_SVI = read_csv(url('https://svi.cdc.gov/Documents/Data/2020_SVI_Data/CSV/SVI2020_US.csv'))%>%
#   write_csv('SVI2020_US.csv')
# 
# CDI_data = read_csv(url('https://data.cdc.gov/api/views/g4ie-h725/rows.csv'))%>%
#   write_csv('CDI_data.csv')

# county_SVI = read_csv(
#   url('https://svi.cdc.gov/Documents/Data/2018_SVI_Data/CSV/SVI2018_US_COUNTY.csv')
#   )%>%
#   write_csv('SVI2018_US_COUNTY.csv')



#census_SVI = read_csv('SVI2020_US.csv')
#county_SVI = read_csv('SVI2018_US_COUNTY.csv')

CDI_fulldata = read_csv('CDI_data.csv')

#CDI_data = read_csv('CDI_2018.csv')
#CDI_fulldata = read_csv('CDI_data.csv')

SVI_2010 = read_csv('SVI2010_US.csv')%>%
  mutate(year = 2010)
SVI_2014 = read_csv('SVI2014_US_COUNTY.csv')%>%
  mutate(year = 2014)
SVI_2016 = read_csv('SVI2016_US_COUNTY.csv')%>%
  mutate(year = 2016)
SVI_2018 = read_csv('SVI2018_US_COUNTY.csv')%>%
  mutate(year = 2018)
SVI_2020 = read_csv('SVI2020_US_COUNTY.csv')%>%
  mutate(year = 2020)
```


```{r 2018cdi}
# read_csv("CDI_2018.csv")%>%
#   filter(Topic == 'Cardiovascular Disease')%>%
#   #group_by(Question)%>%
#   filter(Question =='Mortality from total cardiovascular diseases')%>%
#   filter(DataValueTypeID == 'AGEADJRATE')%>%
#   filter(is.na(DatavalueFootnote))
```
```{r SVI}
state_SVI = SVI_2018%>%
  group_by(ST_ABBR)%>%
  filter(SPL_THEMES>0)%>%
  mutate(popxsvi = E_TOTPOP*SPL_THEMES)%>%
  summarise(state_totpop = sum(E_TOTPOP),state_SVI = sum(popxsvi)/state_totpop)%>%
  mutate(state = ST_ABBR)%>%
  select(state,state_SVI)
  
```


```{r gender difference rate of death from heart disease}
CDI_2018 = read_csv("CDI_2018.csv")
heart = CDI_2018%>%
  mutate(state = LocationAbbr)%>%
  filter(Topic == 'Cardiovascular Disease')%>%
  #group_by(Question)%>%
  filter(Question =='Mortality from total cardiovascular diseases')%>%
  filter(DataValueTypeID == 'AGEADJRATE')%>%
  #dont need this line in app
  filter(is.na(DatavalueFootnote))%>%
  select(LocationAbbr,Stratification1,DataValue)%>%
  pivot_wider(names_from = Stratification1,values_from = DataValue)%>%
  mutate(state = LocationAbbr)%>%
  left_join(state_SVI,"state")
```
```{r heatmap}
 
heatmap = function(cdi, svi){
  df = cdi%>%
    mutate(state = LocationAbbr)%>%
    filter(Topic == 'Cardiovascular Disease')%>%
    #group_by(Question)%>%
    filter(Question =='Mortality from total cardiovascular diseases')%>%
    filter(DataValueTypeID == 'AGEADJRATE')%>%
    select(state,Stratification1,DataValue)
  
  states = unique(df$state)
  groups = unique(df$Stratification1)
  diff_arr = list()
  for (i in groups){
    g1 = df%>%
      filter(Stratification1 == i)
      
    for (j in groups){

      
      g2 = df%>%
        filter(Stratification1 == j)
      
      
      for (state in states){
        print(g1)
        diff = g1[which(g1$state == state),]$DataValue - 
          g2[which(g2$state == state),]$DataValue
        
        diff_arr = append(diff_arr,list(c(state,i,j,diff)))
      }

    }
    
  }
  return()
}

diff_arr = heatmap(CDI_2018,SVI_2018)

```


```{r fit}
c1 = list(c(1,2,3))
c2 = list(c(3,2,1))

c(c1,c2)

```


```{r plot}
ggplot(heart,aes(x = state_SVI,y = gender_diff))+
  geom_point()+
  stat_poly_line(fullrange = TRUE,method='lm')+
  stat_poly_eq(aes(label = after_stat(eq.label)))+
  stat_poly_eq(label.y = 0.9)
```

```{r random}
# question.options = CDI_data%>%
#   filter(Topic == 'Cardiovascular Disease')%>% 
#   {unique(.$Question)}
# 
# CDI_data%>%
#   unite('data_type', DataValueType:DataValueUnit, sep = ' ', remove = TRUE,na.rm = TRUE)  
plot_geo(heart,locationmode='USA-states')%>%
  add_trace(locations = ~state,z = ~gender_diff, color = ~gender_diff,colors = 'Oranges')%>%
  layout(
    title = 'Title WIP: make it some combination of the options',
    geo = c(scope = 'usa',projection = list(type = 'albers usa'))
  )
plot_diff <- function(data,location,value){
  plot_geo(data,locationmode='USA-states')%>%
    add_trace(locations = location,z = value, color = value, colors = 'Oranges')%>%
    layout(
      title = 'Title WIP: make it some combination of the options',
      geo = c(scope = 'usa',projection = list(type = 'albers usa'))
    )
}
plot_diff(heart,~state,~gender_diff)


```

```{r split data}
SVI_2010_new = SVI_2010%>%
  mutate(ST_ABBR = STATE_ABBR)%>%
  mutate(SPL_THEMES = S_PL_THEMES)

SVI_full = bind_rows(SVI_2010_new,SVI_2014,SVI_2016,SVI_2018,SVI_2020)%>%
  
  group_by(year,ST_ABBR)%>%
  filter(SPL_THEMES>0)%>%
  mutate(popxsvi = E_TOTPOP*SPL_THEMES)%>%
  summarise(state_totpop = sum(E_TOTPOP),state_SVI = sum(popxsvi)/state_totpop)%>%
  mutate(state = ST_ABBR)%>%
  select(state,state_SVI)%>%
  write_csv('SVI_full.csv')
```

```{r CDI years}
CDI_fulldata%>%
  filter(YearEnd == 2010)%>%
  write_csv('CDI_2010.csv')
CDI_fulldata%>%
  filter(YearEnd == 2014)%>%
  write_csv('CDI_2014.csv')
CDI_fulldata%>%
  filter(YearEnd == 2016)%>%
  write_csv('CDI_2016.csv')
CDI_fulldata%>%
  filter(YearEnd == 2018)%>%
  write_csv('CDI_2018.csv')
CDI_fulldata%>%
  filter(YearEnd == 2020)%>%
  write_csv('CDI_2020.csv')

```
```{r test}
#CDI_2018 = read_csv('CDI_2018.csv')
# SVI_2010_new%>%
#   group_by(year,ST_ABBR)%>%
#   filter(SPL_THEMES>0)%>%
#   mutate(popxsvi = E_TOTPOP*SPL_THEMES)%>%
#   summarise(state_totpop = sum(E_TOTPOP),state_SVI = sum(popxsvi)/state_totpop)%>%
#   mutate(state = ST_ABBR)%>%
#   select(state,state_SVI)%>%
#   write_csv('SVI_full.csv')
```